# Generated by Django 4.1.3 on 2022-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
