# Using root/example as user/password credentials (not advised for production)

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
