version: '3'

services:
  investment_manager_db:
    image: mysql:8.0.23
    ports:
      - '3306:3306'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: investment_manager
      MYSQL_ROOT_PASSWORD: develop
    volumes:
      - investment_manager_db_data:/var/lib/mysql

  investment_manager:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '5000:5000'
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - investment_manager_db
    tty: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules

volumes:
  investment_manager_db_data:
