services:
  app:
    image: joaop/coderockr
    build:
      context: .
    entrypoint:
     - ./docker-entrypoint.sh
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db
  celery_worker:
    build:
      context: .
    command: |
      wait-for-it rabbitmq:5672
      -- wait-for-it redis:6379
      -- bash -c
      'python -m debugpy --listen 0.0.0.0:5679 -m celery -A coderockr worker -l INFO'
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 5679:5679
    depends_on:
      - rabbitmq
      - redis

  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=coderockr
      - POSTGRES_DB=coderockr
      - POSTGRES_PASSWORD=coderockr
    healthcheck:
      test: 'pg_isready -U coderockr -d coderockr'
      interval: 10s
      timeout: 3s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.10.7-alpine
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=coderockr
      - RABBITMQ_DEFAULT_PASS=coderockr
      - RABBITMQ_DEFAULT_VHOST=coderockr
  redis:
    image: redis:7.0.4-alpine