version: '3.3'

services: 
  app:
    container_name: investment_portfolio_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
  db:
    container_name: investment_portfolio_database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: investment_portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5444:5432"
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"