version: "3.9"

services:

  database:
    image: postgres
    container_name: investments_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: investments_app
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
