[tool.poetry]
name = "events"
version = "0.1.0"
description = ""
authors = ["Luis Guerreiro <devcorujam@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.5"
djangorestframework = "^3.12.2"
django-filter = "^2.4.0"
Pillow = "^8.1.0"
djoser = "^2.1.0"
djangorestframework-simplejwt = "^4.6.0"
python-dotenv = "^0.15.0"
psycopg2-binary = "^2.8.6"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
isort = "^5.7.0"
black = "^20.8b1"
pre-commit = "^2.9.3"
model-bakery = "^1.2.1"
coverage = "^5.3.1"
drf-spectacular = "^0.13.0"
Sphinx = "^3.4.3"
sphinx-redactor-theme = "^0.0.1"
sphinxcontrib-redoc = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 119
