POST http://localhost:3000/createinvestment
Content-Type: application/json

{   
    "creationDate": "2022-01-25T08:12Z",
    "ownerId":10,
    "amount":15000.21
}
### aceita datas yyyy-mm-ddThh:mmz 
##z = zone, Z for Zero, zulu, GMT-0. 
###-0100 for gmt-1, GMT+3 = +0300 etc
#####
GET http://localhost:3000/documentation
Content-Type: application/json
####


GET http://localhost:3000/owner/2
Content-Type: application/json
####

POST http://localhost:3000/createowner
Content-Type: application/json

{
    "firstName":"Lucas",
    "lastName":"Nascimento",
    "email":"email@fake.com",
    "phoneNumber":"11963258874"
}