# Generated by Django 4.1 on 2022-08-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
