# Generated by Django 4.1.3 on 2022-12-06 18:44

from django.db import migrations, models
import investments.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[investments.models.validate_amount],
                    ),
                ),
                (
                    "created_at",
                    models.DateField(validators=[investments.models.validate_date]),
                ),
                (
                    "gains",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                ("withdrawn_date", models.DateField(null=True)),
                (
                    "expected_balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
    ]
