# Generated by Django 4.1 on 2022-08-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='withdrawn_at',
            field=models.DateTimeField(null=True),
        ),
    ]
