# Generated by Django 4.1.3 on 2022-12-04 21:04

from django.db import migrations, models
import investments.models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[investments.models.validate_amount]
            ),
        ),
    ]
