# Generated by Django 4.1 on 2022-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_investment_withdrawn_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
