# Generated by Django 3.1.5 on 2021-01-19 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add__event__participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("EV", "Event"), ("FS", "Friendship")],
                        help_text="EV = Event Invitation | FS = Frienship Invitation",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("AC", "Accepted"), ("RE", "Rejected"), ("PE", "Pending")],
                        default="PE",
                        help_text="AC = Accepted | RE = Rejected | PE = Pending\nDefault is PE",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        related_query_name="invitation",
                        to="core.event",
                    ),
                ),
                (
                    "invitation_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_sended",
                        related_query_name="invitation_sended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_received",
                        related_query_name="invitation_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("type", "event", "invitation_from", "invitation_to")},
            },
        ),
    ]
