# Generated by Django 3.1.5 on 2021-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add__event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
