# Generated by Django 4.1.2 on 2022-10-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adress')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
