version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nestjs-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: app-db
    restart: always
    tty: true
    ports:
      - '5433:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=appdb
  dbtest:
    build: .docker/postgres
    container_name: app-dbtest
    restart: always
    tty: true
    ports:
      - '5434:5432'
    volumes:
      - .docker/dbdatatest:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=testdb
