# Generated by Django 4.1 on 2022-08-17 04:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='created in')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='investment.owner', verbose_name='owner')),
            ],
        ),
    ]
