# Generated by Django 4.1 on 2022-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investments_balance_investments_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True, verbose_name='withdrawal date'),
        ),
    ]
