const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.invest = require("./invest.model.js")(mongoose);
db.owner = require("./owner.model.js")(mongoose);
module.exports = db;