# Generated by Django 4.1.2 on 2022-10-19 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('initial_amount', models.FloatField()),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='persons.person')),
            ],
            options={
                'verbose_name': 'Investment',
            },
        ),
    ]
